# Working_with_Data_Part_2

# Merge

In [10]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
dframe1 = DataFrame({'key':['X','Z','Y','Z','X','X',], 'Data_set_1':np.arange(6)})
dframe1

Data_set_1 key
0           0   X
1           1   Z
2           2   Y
3           3   Z
4           4   X
5           5   X

In [3]:
dframe2 = DataFrame({'key':['Q','Y','Z'],'data_set_2':[1,2,3]})
dframe2

data_set_2 key
0           1   Q
1           2   Y
2           3   Z

In [4]:
pd.merge(dframe1,dframe2)

Data_set_1 key  data_set_2
0           1   Z           3
1           3   Z           3
2           2   Y           2

In [5]:
pd.merge(dframe1,dframe2,on='key')

Data_set_1 key  data_set_2
0           1   Z           3
1           3   Z           3
2           2   Y           2

In [6]:
pd.merge(dframe1,dframe2,on='key',how='left')

Data_set_1 key  data_set_2
0           0   X         NaN
1           1   Z         3.0
2           2   Y         2.0
3           3   Z         3.0
4           4   X         NaN
5           5   X         NaN

In [10]:
pd.merge(dframe1,dframe2,on='key',how='right')

Data_set_1 key  data_set_2
0         1.0   Z           3
1         3.0   Z           3
2         2.0   Y           2
3         NaN   Q           1

In [11]:
pd.merge(dframe1,dframe2,on='key',how='outer')

Data_set_1 key  data_set_2
0         0.0   X         NaN
1         4.0   X         NaN
2         5.0   X         NaN
3         1.0   Z         3.0
4         3.0   Z         3.0
5         2.0   Y         2.0
6         NaN   Q         1.0

In [12]:
dframe3 = DataFrame({'key':['X','X','X','Y','Z','Z'],'data_set_3':range(6)})

In [13]:
dframe4 = DataFrame({'key':['Y','Y','X','X','Z'],'data_set_4':range(5)})

In [14]:
dframe3

data_set_3 key
0           0   X
1           1   X
2           2   X
3           3   Y
4           4   Z
5           5   Z

In [15]:
dframe4

data_set_4 key
0           0   Y
1           1   Y
2           2   X
3           3   X
4           4   Z

In [16]:
pd.merge(dframe3,dframe4)

data_set_3 key  data_set_4
0           0   X           2
1           0   X           3
2           1   X           2
3           1   X           3
4           2   X           2
5           2   X           3
6           3   Y           0
7           3   Y           1
8           4   Z           4
9           5   Z           4

In [18]:
df_left = DataFrame({'key1':['SF','SF','LA'],'key2':['one','two','one'],'left_data':[10,20,30]})

In [19]:
df_right = DataFrame({'key1':['SF','SF','LA','LA'],'key2':['one','one','one','two'],'right_dat':[40,50,60,70,]})

In [20]:
df_left

key1 key2  left_data
0   SF  one         10
1   SF  two         20
2   LA  one         30

In [21]:
df_right

key1 key2  right_dat
0   SF  one         40
1   SF  one         50
2   LA  one         60
3   LA  two         70

In [23]:
pd.merge(df_left,df_right,on=['key1','key2'],how='outer')

key1 key2  left_data  right_dat
0   SF  one       10.0       40.0
1   SF  one       10.0       50.0
2   SF  two       20.0        NaN
3   LA  one       30.0       60.0
4   LA  two        NaN       70.0

In [24]:
pd.merge(df_left,df_right, on='key1')

key1 key2_x  left_data key2_y  right_dat
0   SF    one         10    one         40
1   SF    one         10    one         50
2   SF    two         20    one         40
3   SF    two         20    one         50
4   LA    one         30    one         60
5   LA    one         30    two         70

In [25]:
pd.merge(df_left,df_right,on='key1',suffixes=('_lefty','_righty'))

key1 key2_lefty  left_data key2_righty  right_dat
0   SF        one         10         one         40
1   SF        one         10         one         50
2   SF        two         20         one         40
3   SF        two         20         one         50
4   LA        one         30         one         60
5   LA        one         30         two         70

In [26]:
url = 'http://pandas.pydata.org/pandas-docs/dev/generated/pandas.DataFrame.merge.html'

# Merge_on_Index

In [11]:
df_left = DataFrame({'key':['X','Y','Z','X','Y'],'data':range(5)})
df_left

data key
0     0   X
1     1   Y
2     2   Z
3     3   X
4     4   Y

In [13]:
df_right = DataFrame({'group_data':[10,20]},index=['X','Y'])
df_right

group_data
X          10
Y          20

In [14]:
pd.merge(df_left,df_right,left_on='key',right_index=True)

data key  group_data
0     0   X          10
3     3   X          10
1     1   Y          20
4     4   Y          20

In [17]:
df_left_hr =DataFrame({'key1':['SF','SF','SF','LA','LA'],
                      'key2':[10,20,30,20,30],
                      'data_set':np.arange(5.)})
df_left_hr

data_set key1  key2
0       0.0   SF    10
1       1.0   SF    20
2       2.0   SF    30
3       3.0   LA    20
4       4.0   LA    30

In [18]:
df_right_hr = DataFrame(np.arange(10).reshape(5,2),
                        index=[['LA','LA','SF','SF','SF'],[20,10,10,10,10,]],
                       columns=['col_1','col_2'])
df_right_hr

col_1  col_2
LA 20      0      1
   10      2      3
SF 10      4      5
   10      6      7
   10      8      9

In [19]:
pd.merge(df_left_hr,df_right_hr,left_on=['key1','key2'],right_index=True)

data_set key1  key2  col_1  col_2
0       0.0   SF    10      4      5
0       0.0   SF    10      6      7
0       0.0   SF    10      8      9
3       3.0   LA    20      0      1

In [20]:
df_left.join(df_right)

data key  group_data
0     0   X         NaN
1     1   Y         NaN
2     2   Z         NaN
3     3   X         NaN
4     4   Y         NaN

In [21]:
df_right.join(df_left)

group_data  data  key
X          10   NaN  NaN
Y          20   NaN  NaN

# Concatenate

In [23]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [25]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])

In [27]:
ser1

T    0
U    1
V    2
dtype: int64

In [28]:
ser2

X    3
Y    4
dtype: int64

In [29]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [30]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [31]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [32]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [33]:
dframe1

X         Y         Z
0  0.384852 -0.468127 -0.571125
1 -1.129463  0.167012  3.131378
2 -1.405696 -0.397281 -1.100083
3  1.392618  0.418226  0.944754

In [34]:
dframe2

Y         Q         X
0  0.836691 -0.464237 -0.337100
1 -0.611494  0.677737 -0.306182
2 -0.796258  0.224778 -0.513121

In [35]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN  0.384852 -0.468127 -0.571125
1       NaN -1.129463  0.167012  3.131378
2       NaN -1.405696 -0.397281 -1.100083
3       NaN  1.392618  0.418226  0.944754
0 -0.464237 -0.337100  0.836691       NaN
1  0.677737 -0.306182 -0.611494       NaN
2  0.224778 -0.513121 -0.796258       NaN

In [36]:
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN  0.384852 -0.468127 -0.571125
1       NaN -1.129463  0.167012  3.131378
2       NaN -1.405696 -0.397281 -1.100083
3       NaN  1.392618  0.418226  0.944754
4 -0.464237 -0.337100  0.836691       NaN
5  0.677737 -0.306182 -0.611494       NaN
6  0.224778 -0.513121 -0.796258       NaN

In [37]:
url = 'http://pandas.pydata.org/pandas-docs/dev/generated/pandas.tools.merge.concat.html'

# Combining_DataFrames

In [38]:
ser1 = Series([2,np.nan,4,np.nan,6,np.nan],
             index=['Q','R','S','T','U','V'])
ser1

Q    2.0
R    NaN
S    4.0
T    NaN
U    6.0
V    NaN
dtype: float64

In [39]:
ser2 = Series(np.arange(len(ser1)),dtype=np.float64,
             index=['Q','R','S','T','U','V'])
ser2

Q    0.0
R    1.0
S    2.0
T    3.0
U    4.0
V    5.0
dtype: float64

In [40]:
Series(np.where(pd.isnull(ser1),ser2,ser1),index=ser1.index)

Q    2.0
R    1.0
S    4.0
T    3.0
U    6.0
V    5.0
dtype: float64

In [41]:
ser1.combine_first(ser2)

Q    2.0
R    1.0
S    4.0
T    3.0
U    6.0
V    5.0
dtype: float64

In [42]:
nan = np.nan
dframe_odds = DataFrame({'X':[1.,nan,3.,nan],
                        'Y':[nan,5.,nan,7.],
                        'Z':[nan,9.,nan,11.]})
dframe_odds

X    Y     Z
0  1.0  NaN   NaN
1  NaN  5.0   9.0
2  3.0  NaN   NaN
3  NaN  7.0  11.0

In [43]:
dframe_evens = DataFrame({'X':[2.,4.,nan,6.,8.],
                        'Y':[nan,10.,12.,14.,16.]})
dframe_evens

X     Y
0  2.0   NaN
1  4.0  10.0
2  NaN  12.0
3  6.0  14.0
4  8.0  16.0

In [44]:
dframe_odds.combine_first(dframe_evens)

X     Y     Z
0  1.0   NaN   NaN
1  4.0   5.0   9.0
2  3.0  12.0   NaN
3  6.0   7.0  11.0
4  8.0  16.0   NaN

# Reshaping 

In [46]:
dframe1= DataFrame(np.arange(8).reshape(2,4),
                 index=pd.Index(['LA','SF'],name='city'),
                 columns=pd.Index(['A','B','C','D'],name='letter'))
dframe1

letter  A  B  C  D
city              
LA      0  1  2  3
SF      4  5  6  7

In [47]:
dframe_st= dframe1.stack()
dframe_st

city  letter
LA    A         0
      B         1
      C         2
      D         3
SF    A         4
      B         5
      C         6
      D         7
dtype: int32

In [48]:
dframe_st.unstack()

letter  A  B  C  D
city              
LA      0  1  2  3
SF      4  5  6  7

In [49]:
dframe_st.unstack('city')

city    LA  SF
letter        
A        0   4
B        1   5
C        2   6
D        3   7

In [50]:
ser1 = Series([0,1,2],index=['Q','X','Y'])
ser2 = Series([4,5,6],index=['X','Y','Z'])

In [51]:
dframe = pd.concat([ser1,ser2],keys=['Alpha','Beta'])
dframe

Alpha  Q    0
       X    1
       Y    2
Beta   X    4
       Y    5
       Z    6
dtype: int64

In [52]:
dframe.unstack()

Q    X    Y    Z
Alpha  0.0  1.0  2.0  NaN
Beta   NaN  4.0  5.0  6.0

In [53]:
dframe.unstack().stack()

Alpha  Q    0.0
       X    1.0
       Y    2.0
Beta   X    4.0
       Y    5.0
       Z    6.0
dtype: float64

In [54]:
dframe = dframe.unstack()
dframe

Q    X    Y    Z
Alpha  0.0  1.0  2.0  NaN
Beta   NaN  4.0  5.0  6.0

In [55]:
dframe.stack()

Alpha  Q    0.0
       X    1.0
       Y    2.0
Beta   X    4.0
       Y    5.0
       Z    6.0
dtype: float64

In [56]:
dframe.stack(dropna=False)

Alpha  Q    0.0
       X    1.0
       Y    2.0
       Z    NaN
Beta   Q    NaN
       X    4.0
       Y    5.0
       Z    6.0
dtype: float64

# Pivoting

In [57]:
# Lets create some data to play with:

# Note: It is not necessary to understand how this dataset was made to understand this Lecture.

#import pandas testing utility
import pandas.util.testing as tm; tm.N = 3

#Create a unpivoted function
def unpivot(frame):
    N, K = frame.shape
    
    data = {'value' : frame.values.ravel('F'),
            'variable' : np.asarray(frame.columns).repeat(N),
            'date' : np.tile(np.asarray(frame.index), K)}
    
    # Return the DataFrame
    return DataFrame(data, columns=['date', 'variable', 'value'])

#Set the DataFrame we'll be using
dframe = unpivot(tm.makeTimeDataFrame())

In [58]:
dframe

date variable     value
0  2000-01-03        A -0.358136
1  2000-01-04        A -0.574024
2  2000-01-05        A  0.615123
3  2000-01-03        B -0.856737
4  2000-01-04        B  0.400978
5  2000-01-05        B  0.559924
6  2000-01-03        C -1.335036
7  2000-01-04        C  1.993885
8  2000-01-05        C  1.434605
9  2000-01-03        D -0.938663
10 2000-01-04        D  0.430247
11 2000-01-05        D -1.137625

In [59]:
dframe_piv = dframe.pivot('date','variable','value')

In [60]:
dframe_piv

variable           A         B         C         D
date                                              
2000-01-03 -0.358136 -0.856737 -1.335036 -0.938663
2000-01-04 -0.574024  0.400978  1.993885  0.430247
2000-01-05  0.615123  0.559924  1.434605 -1.137625

In [64]:
dframe.pivot_table('value','date','variable')

variable           A         B         C         D
date                                              
2000-01-03 -0.358136 -0.856737 -1.335036 -0.938663
2000-01-04 -0.574024  0.400978  1.993885  0.430247
2000-01-05  0.615123  0.559924  1.434605 -1.137625

# Duplicates_in_DataFrames

In [68]:
dframe= DataFrame({'key1':['A']*2 + ['B']*3,
                  'key2':[2,2,2,3,3]})
dframe

key1  key2
0    A     2
1    A     2
2    B     2
3    B     3
4    B     3

In [69]:
dframe.duplicated()

0    False
1     True
2    False
3    False
4     True
dtype: bool

In [70]:
dframe.drop_duplicates()

key1  key2
0    A     2
2    B     2
3    B     3

In [71]:
dframe.drop_duplicates(['key1'])

key1  key2
0    A     2
2    B     2

In [72]:
dframe.drop_duplicates(['key2'])

key1  key2
0    A     2
3    B     3

In [74]:
dframe.drop_duplicates(['key1'],keep='last')

key1  key2
1    A     2
4    B     3

# Mapping

In [75]:
dframe = DataFrame({'city':['Alma','Brian Head','Fox Park'],
                   'altitude':[3158,3000,2762]})
dframe

altitude        city
0      3158        Alma
1      3000  Brian Head
2      2762    Fox Park

In [76]:
state_map = {'Alma':'Colorado','Brian Head':'Utah','Fox Park':'Wyoming'}

In [77]:
dframe['state'] = dframe['city'].map(state_map)

In [78]:
dframe

altitude        city     state
0      3158        Alma  Colorado
1      3000  Brian Head      Utah
2      2762    Fox Park   Wyoming

# Replace

In [79]:
ser1 = Series([1,2,3,4,1,2,3,4])
ser1

0    1
1    2
2    3
3    4
4    1
5    2
6    3
7    4
dtype: int64

In [81]:
ser1.replace(1,np.nan)

0    NaN
1    2.0
2    3.0
3    4.0
4    NaN
5    2.0
6    3.0
7    4.0
dtype: float64

In [83]:
ser1.replace([1,4],[100,400])

0    100
1      2
2      3
3    400
4    100
5      2
6      3
7    400
dtype: int64

In [84]:
ser1.replace({4:np.nan})

0    1.0
1    2.0
2    3.0
3    NaN
4    1.0
5    2.0
6    3.0
7    NaN
dtype: float64

# Renameing_Index

In [86]:
dframe = DataFrame(np.arange(12).reshape(3,4),
                   index=['NY','LA','SF'],
                  columns=['A','B','C','D'])
dframe

A  B   C   D
NY  0  1   2   3
LA  4  5   6   7
SF  8  9  10  11

In [87]:
dframe.index.map(str.lower)

Index(['ny', 'la', 'sf'], dtype='object')

In [89]:
dframe.index = dframe.index.map(str.lower)

In [90]:
dframe

A  B   C   D
ny  0  1   2   3
la  4  5   6   7
sf  8  9  10  11

In [91]:
dframe.rename(index=str.title,columns=str.lower)

a  b   c   d
Ny  0  1   2   3
La  4  5   6   7
Sf  8  9  10  11

In [92]:
dframe.rename(index={'ny':'New York'},
             columns={'A':'ALPHA'})

ALPHA  B   C   D
New York      0  1   2   3
la            4  5   6   7
sf            8  9  10  11

In [93]:
dframe

A  B   C   D
ny  0  1   2   3
la  4  5   6   7
sf  8  9  10  11

In [94]:
dframe.rename(index={'ny':'New York'},
             inplace=True)

In [95]:
dframe

A  B   C   D
New York  0  1   2   3
la        4  5   6   7
sf        8  9  10  11

# Binning

In [96]:
years = [1990,1991,1992,2008,2012,2015,1987,1969,2013,2008,1999]
decade_bins = [1960,1970,1980,1990,2000,2010,2020]

In [97]:
decade_cat = pd.cut(years,decade_bins)

In [98]:
decade_cat

[(1980, 1990], (1990, 2000], (1990, 2000], (2000, 2010], (2010, 2020], ..., (1980, 1990], (1960, 1970], (2010, 2020], (2000, 2010], (1990, 2000]]
Length: 11
Categories (6, interval[int64]): [(1960, 1970] < (1970, 1980] < (1980, 1990] < (1990, 2000] < (2000, 2010] < (2010, 2020]]

In [99]:
decade_cat.categories

IntervalIndex([(1960, 1970], (1970, 1980], (1980, 1990], (1990, 2000], (2000, 2010], (2010, 2020]]
              closed='right',
              dtype='interval[int64]')

In [100]:
pd.value_counts(decade_cat)

(2010, 2020]    3
(1990, 2000]    3
(2000, 2010]    2
(1980, 1990]    2
(1960, 1970]    1
(1970, 1980]    0
dtype: int64

In [101]:
pd.cut(years,2,precision=1)

[(1969.0, 1992.0], (1969.0, 1992.0], (1969.0, 1992.0], (1992.0, 2015.0], (1992.0, 2015.0], ..., (1969.0, 1992.0], (1969.0, 1992.0], (1992.0, 2015.0], (1992.0, 2015.0], (1992.0, 2015.0]]
Length: 11
Categories (2, interval[float64]): [(1969.0, 1992.0] < (1992.0, 2015.0]]

# Outliers

In [102]:
np.random.seed(12345)

In [103]:
dframe = DataFrame(np.random.randn(1000,4))

In [104]:
dframe.head()

0         1         2         3
0 -0.204708  0.478943 -0.519439 -0.555730
1  1.965781  1.393406  0.092908  0.281746
2  0.769023  1.246435  1.007189 -1.296221
3  0.274992  0.228913  1.352917  0.886429
4 -2.001637 -0.371843  1.669025 -0.438570

In [105]:
dframe.tail()

0         1         2         3
995  1.089085  0.251232 -1.451985  1.653126
996 -0.478509 -0.010663 -1.060881 -1.502870
997 -1.946267  1.013592  0.037333  0.133304
998 -1.293122 -0.322542 -0.782960 -0.303340
999  0.089987  0.292291  1.177706  0.882755

In [106]:
dframe.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528

In [107]:
col = dframe[0]

In [108]:
col.head()

0   -0.204708
1    1.965781
2    0.769023
3    0.274992
4   -2.001637
Name: 0, dtype: float64

In [109]:
col[np.abs(col)>3]

523   -3.428254
900    3.366626
Name: 0, dtype: float64

In [110]:
dframe[(np.abs(dframe)>3).any(1)]

0         1         2         3
5   -0.539741  0.476985  3.248944 -1.021228
97  -0.774363  0.552936  0.106061  3.927528
102 -0.655054 -0.565230  3.176873  0.959533
305 -2.315555  0.457246 -0.025907 -3.399312
324  0.050188  1.951312  3.260383  0.963301
400  0.146326  0.508391 -0.196713 -3.745356
499 -0.293333 -0.242459 -3.056990  1.918403
523 -3.428254 -0.296336 -0.439938 -0.867165
586  0.275144  1.179227 -3.184377  1.369891
808 -0.362528 -3.548824  1.553205 -2.186301
900  3.366626 -2.372214  0.851010  1.332846

In [111]:
dframe[np.abs(dframe)>3] = np.sign(dframe)*3

In [112]:
dframe.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067623     0.068473     0.025153    -0.002081
std       0.995485     0.990253     1.003977     0.989736
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.000000     2.653656     3.000000     3.000000

# Permutation

In [113]:
dframe= DataFrame(np.arange(16).reshape(4,4))

In [114]:
blender = np.random.permutation(4)

In [115]:
blender

array([1, 3, 2, 0])

In [116]:
dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [117]:
dframe.take(blender)

0   1   2   3
1   4   5   6   7
3  12  13  14  15
2   8   9  10  11
0   0   1   2   3

In [118]:
box = np.array([1,2,3])

In [119]:
shaker=np.random.randint(0,len(box),size=10)

In [120]:
shaker

array([2, 0, 2, 0, 2, 0, 2, 0, 2, 2])

In [121]:
hand_gabs= box.take(shaker)
hand_gabs

array([3, 1, 3, 1, 3, 1, 3, 1, 3, 3])